-- ===========================================================================
-- Volume — workout tracker
-- SOURCE OF TRUTH for the database. Change this file FIRST, then paste the
-- changed part into the Supabase SQL editor and run it.
--
-- Packet 2: core schema (sessions, movement_patterns, exercises,
-- session_exercises, sets).
--
-- Safe to run more than once — every statement is written so that re-running
-- it does nothing harmful.
--
-- Run order matters: sessions and movement_patterns must exist before
-- exercises (which points at movement_patterns), and exercises and sessions
-- must exist before session_exercises and sets (which point at them).
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- Conventions used throughout
--
--   * ids are uuid, generated by the database
--   * every timestamp is `timestamptz`, which Postgres stores in UTC.
--     The UI converts to local time on the way out. Never store local time.
--   * `deleted_at` is the soft delete: NULL means live, a timestamp means
--     "in the recently-deleted bin". Nothing is actually removed, so queries
--     for live data must say `where deleted_at is null`.
--   * `sets` has no soft delete — deleting a set really deletes it.
-- ---------------------------------------------------------------------------


-- ===========================================================================
-- 1. sessions — one workout day
-- ===========================================================================

create table if not exists public.sessions (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,

  -- The split / category for the day: "legs", "push", "pull", …
  -- Free text on purpose, so adding a new split doesn't need a schema change.
  -- Nullable so you can hit "start workout" and tag it a moment later.
  category    text,

  start_time  timestamptz not null default now(),
  -- NULL while the session is still in progress.
  end_time    timestamptz,

  -- How the whole day went.
  comment     text,

  deleted_at  timestamptz,
  created_at  timestamptz not null default now(),

  -- A session can't finish before it started.
  constraint sessions_end_after_start check (end_time is null or end_time >= start_time)
);

create index if not exists sessions_user_start_idx
  on public.sessions (user_id, start_time desc);

-- Speeds up the "recently deleted" view and the normal "live sessions" list.
create index if not exists sessions_user_live_idx
  on public.sessions (user_id, start_time desc)
  where deleted_at is null;


-- ===========================================================================
-- 2. movement_patterns — the "boxes" exercises live in, e.g. "Horizontal
--    Press". A pure category: just a name. It is never something you log a
--    set against directly, so unlike exercises it has no `type` at all.
-- ===========================================================================

create table if not exists public.movement_patterns (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,

  name        text not null,

  -- Which session type this box belongs to, e.g. "Push". Free text, same as
  -- sessions.category — matched case-insensitively against it so the Log
  -- screen can show "your Push patterns" first when you start a Push
  -- session. Nullable: a pattern doesn't have to be tied to a session type.
  category    text,

  deleted_at  timestamptz,
  created_at  timestamptz not null default now(),

  constraint movement_patterns_name_not_blank check (length(btrim(name)) > 0)
);

-- Brings an already-existing movement_patterns table up to the current
-- shape. No-op on a brand new database.
alter table public.movement_patterns add column if not exists category text;

create index if not exists movement_patterns_user_idx
  on public.movement_patterns (user_id);

create index if not exists movement_patterns_category_idx
  on public.movement_patterns (user_id, lower(btrim(category)))
  where category is not null and deleted_at is null;

-- Same reasoning as the exercise name index below: no two live boxes with
-- the same name, but a deleted one frees the name back up.
create unique index if not exists movement_patterns_unique_live_name
  on public.movement_patterns (user_id, lower(btrim(name)))
  where deleted_at is null;


-- ---------------------------------------------------------------------------
-- Deleting a box takes what's currently inside it with it — "throwing away
-- a box full of stuff". Restoring the box only brings back what was thrown
-- out *with* it: anything deleted individually beforehand keeps its own
-- (different) deleted_at and stays deleted. That's what the timestamp
-- comparison on restore is doing — it's the only way to tell "was this
-- deleted as part of the box" apart from "was this already gone".
-- ---------------------------------------------------------------------------

create or replace function public.cascade_movement_pattern_delete()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if new.deleted_at is not null and old.deleted_at is null then
    update public.exercises
      set deleted_at = new.deleted_at
      where movement_pattern_id = new.id
        and deleted_at is null;
  elsif new.deleted_at is null and old.deleted_at is not null then
    update public.exercises
      set deleted_at = null
      where movement_pattern_id = new.id
        and deleted_at = old.deleted_at;
  end if;
  return new;
end;
$$;

drop trigger if exists movement_patterns_cascade_delete on public.movement_patterns;

create trigger movement_patterns_cascade_delete
  after update of deleted_at on public.movement_patterns
  for each row
  execute function public.cascade_movement_pattern_delete();


-- ===========================================================================
-- 2b. session_types — the managed list of session-type chips, set in
--     Settings. Deliberately NOT referenced by a foreign key from anywhere:
--     sessions.category and movement_patterns.category stay plain text,
--     copied at selection time. Deleting a type here can never rewrite or
--     orphan a session/pattern that already used it — that's what lets old
--     history keep showing a split you've since stopped using.
-- ===========================================================================

create table if not exists public.session_types (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,

  name        text not null,

  created_at  timestamptz not null default now(),

  constraint session_types_name_not_blank check (length(btrim(name)) > 0)
);

create index if not exists session_types_user_idx
  on public.session_types (user_id);

-- One "Push" per user — case-insensitively, same reasoning as
-- movement_patterns' name uniqueness.
create unique index if not exists session_types_unique_name
  on public.session_types (user_id, lower(btrim(name)));


-- ===========================================================================
-- 3. exercises — exercise definitions, independent of any session
-- ===========================================================================

create table if not exists public.exercises (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null references auth.users (id) on delete cascade,

  name                  text not null,

  -- Locked after the first set is logged — see the trigger further down.
  -- 'assisted' inverts what counts as progress (less assistance is better),
  -- so changing this later would silently corrupt PR and history maths.
  type                  text not null,

  -- One side at a time (a single-leg calf raise, a single-arm row) rather
  -- than both together. Also locked after the first set — see the trigger
  -- further down. Doesn't affect PR/index math like type does; it's locked
  -- for a lighter reason, so old sets' limiting_side (see sets table) keeps
  -- meaning what it meant when logged.
  unilateral            boolean not null default false,

  -- Which box this exercise lives in, e.g. "Bench Press" -> "Horizontal
  -- Press". Nullable: an exercise doesn't have to belong to a pattern.
  -- ON DELETE SET NULL is a fallback for a pattern removed outside the app
  -- (e.g. by hand in the SQL editor) — in normal use the cascade trigger
  -- above handles it via soft delete before this would ever fire.
  movement_pattern_id   uuid references public.movement_patterns (id) on delete set null,

  -- Notes that stay attached to the exercise itself: "seat height 4",
  -- "keep elbows tucked". Not day-specific — that's session_exercises.
  persistent_notes      text,

  deleted_at            timestamptz,
  created_at            timestamptz not null default now(),

  -- The allowed types, enforced by the database rather than by trust.
  -- 'assisted' is legacy-only — no longer offered when creating a new
  -- exercise (superseded by 'bodyweight', see the sets table below), but an
  -- exercise already locked to it keeps working exactly as before.
  constraint exercises_type_valid
    check (type in ('weight_reps', 'time_based', 'assisted', 'bodyweight')),

  constraint exercises_name_not_blank
    check (length(btrim(name)) > 0)
);

-- Widen an already-existing type constraint to include 'bodyweight'. No-op
-- on a brand new database, since the create table above already allows it.
alter table public.exercises drop constraint if exists exercises_type_valid;
alter table public.exercises add constraint exercises_type_valid
  check (type in ('weight_reps', 'time_based', 'assisted', 'bodyweight'));

-- Brings an already-existing exercises table (from before movement_patterns
-- existed) up to the current shape. No-ops on a brand new database, since
-- the create table above already has the right columns from the start.
alter table public.exercises drop constraint if exists exercises_no_self_parent;
drop index if exists public.exercises_parent_idx;
alter table public.exercises drop column if exists parent_exercise_id;
alter table public.exercises
  add column if not exists movement_pattern_id uuid references public.movement_patterns (id) on delete set null;
alter table public.exercises add column if not exists unilateral boolean not null default false;

create index if not exists exercises_user_idx
  on public.exercises (user_id);

create index if not exists exercises_movement_pattern_idx
  on public.exercises (movement_pattern_id)
  where movement_pattern_id is not null;

-- Stops two live exercises sharing a name (case-insensitively), which would
-- split one exercise's history across two rows and break PR tracking.
-- Deleted ones are excluded, so the name frees up again after a delete.
create unique index if not exists exercises_unique_live_name
  on public.exercises (user_id, lower(btrim(name)))
  where deleted_at is null;


-- ===========================================================================
-- 4. session_exercises — one exercise's comment (and extra-flag) for one
--    specific day
-- ===========================================================================
-- Comment e.g. "hamstring felt bad, didn't go up in weight" — true of leg
-- curls on Tuesday, not of leg curls in general.
--
-- Kept separate from `sets` so the comment survives deleting every set, and
-- can be written before the first set is logged.

create table if not exists public.session_exercises (
  id           uuid primary key default gen_random_uuid(),
  session_id   uuid not null references public.sessions (id)  on delete cascade,
  exercise_id  uuid not null references public.exercises (id) on delete cascade,

  comment      text,

  -- Marks a rep-out that isn't really today's focus — a few pull-ups
  -- tacked onto the end of a push day, not a genuine attempt at the
  -- movement. Still counts toward the strength index (it's real training,
  -- and the index already smooths out a single off day across many
  -- sessions) — the flag only changes the volume donut, where it shows as
  -- its own "Extra" slice instead of getting filed under the session's
  -- category, so a bonus pull-up doesn't count as Push volume.
  is_extra     boolean not null default false,

  created_at   timestamptz not null default now(),

  -- One comment row per exercise per session.
  constraint session_exercises_unique_pair unique (session_id, exercise_id)
);

-- Brings an already-existing session_exercises table up to the current
-- shape. No-op on a brand new database.
alter table public.session_exercises add column if not exists is_extra boolean not null default false;

create index if not exists session_exercises_session_idx
  on public.session_exercises (session_id);

create index if not exists session_exercises_exercise_idx
  on public.session_exercises (exercise_id);


-- ===========================================================================
-- 5. sets — individual sets logged in a session, against an exercise
-- ===========================================================================
-- Hard delete only. No deleted_at here: a mistyped set is faster to re-enter
-- than to recover.
--
-- Which columns get used depends on the exercise's type:
--   weight_reps  → weight + reps
--   assisted     → weight (the assistance) + reps
--   time_based   → duration_seconds
--   bodyweight   → weight (delta magnitude) + weight_direction + bodyweight_kg (snapshot) + reps
-- That pairing isn't enforced by a constraint, because the type lives on
-- another table; the Log screen is responsible for filling the right fields.

create table if not exists public.sets (
  id                uuid primary key default gen_random_uuid(),

  -- Deleting a session for real takes its sets with it. Note that ordinary
  -- deletes are soft, so this only fires when a session is truly purged.
  session_id        uuid not null references public.sessions (id) on delete cascade,

  -- RESTRICT, not CASCADE: an exercise with logged history can't be hard
  -- deleted out from under its sets. You'd get a loud error instead of
  -- silently losing months of training history.
  exercise_id       uuid not null references public.exercises (id) on delete restrict,

  -- Kilograms. Always kg, everywhere, no exceptions.
  -- For 'assisted' this is how much help the machine gave — lower is better.
  -- For 'bodyweight' this is a delta magnitude (see weight_direction below),
  -- not the effective load itself.
  weight            numeric(6, 2),

  reps              integer,

  -- Only used by 'time_based' exercises (planks, dead hangs, …).
  duration_seconds  integer,

  -- 'bodyweight' only: which way `weight` above pushes the effective load —
  -- 'assist' (less than bodyweight) or 'add' (more than bodyweight). Null
  -- when weight is 0 (plain bodyweight, direction is meaningless).
  weight_direction  text,

  -- 'bodyweight' only: a snapshot of the user's bodyweight (from
  -- body_weights) at the moment this set was logged. Captured once and
  -- never recomputed, so correcting an old body_weights entry later can't
  -- silently reshuffle historical PRs. effective load = bodyweight_kg +
  -- (weight_direction = 'assist' ? -weight : weight).
  bodyweight_kg     numeric(5, 2),

  -- Fixed small vocabulary chosen in the UI: "failed last rep", "grind", …
  -- Text rather than an enum so adding a tag doesn't need a migration.
  quick_tag         text,

  -- Unilateral exercises only. Which side actually decided the tag above —
  -- you cap the stronger side to match the weaker one while training, so
  -- the rep count is already honest for both; this records which side was
  -- the real limiting factor. Only ever asked for alongside 'hard' or
  -- 'failure' — an 'easy' set didn't get limited by either side.
  limiting_side     text,

  note              text,

  created_at        timestamptz not null default now(),

  constraint sets_weight_sane   check (weight is null or weight >= 0),
  constraint sets_reps_sane     check (reps is null or reps > 0),
  constraint sets_duration_sane check (duration_seconds is null or duration_seconds > 0),
  constraint sets_weight_direction_valid
    check (weight_direction is null or weight_direction in ('assist', 'add')),
  constraint sets_bodyweight_sane
    check (bodyweight_kg is null or (bodyweight_kg > 20 and bodyweight_kg < 500)),
  constraint sets_limiting_side_valid
    check (limiting_side is null or limiting_side in ('left', 'right', 'even')),

  -- A set has to record something.
  constraint sets_not_empty
    check (reps is not null or duration_seconds is not null or weight is not null)
);

-- Brings an already-existing sets table up to the current shape. No-ops on a
-- brand new database, since the create table above already has these columns.
alter table public.sets add column if not exists weight_direction text;
alter table public.sets add column if not exists bodyweight_kg numeric(5, 2);
alter table public.sets add column if not exists limiting_side text;
alter table public.sets drop constraint if exists sets_weight_direction_valid;
alter table public.sets add constraint sets_weight_direction_valid
  check (weight_direction is null or weight_direction in ('assist', 'add'));
alter table public.sets drop constraint if exists sets_bodyweight_sane;
alter table public.sets add constraint sets_bodyweight_sane
  check (bodyweight_kg is null or (bodyweight_kg > 20 and bodyweight_kg < 500));
alter table public.sets drop constraint if exists sets_limiting_side_valid;
alter table public.sets add constraint sets_limiting_side_valid
  check (limiting_side is null or limiting_side in ('left', 'right', 'even'));

-- Fetching a session's sets in the order they were logged.
create index if not exists sets_session_idx
  on public.sets (session_id, created_at);

-- The index PR and history maths lean on: every set for one exercise, newest
-- first.
create index if not exists sets_exercise_idx
  on public.sets (exercise_id, created_at desc);


-- ===========================================================================
-- 5b. body_weights — bodyweight readings, independent of any workout
-- ===========================================================================
-- Hard delete only, same reasoning as sets: a mistyped reading is quicker to
-- retype than to recover.

create table if not exists public.body_weights (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,

  -- Kilograms, always. One decimal is what a bathroom scale actually shows,
  -- but the column keeps two so a stray 80.55 can't be silently truncated on
  -- the way in — rounding is the UI's job, not the database's.
  weight_kg    numeric(5, 2) not null,

  -- Stored UTC, shown local, like every other timestamp here.
  measured_at  timestamptz not null default now(),

  -- Older readings were written down as a date with no clock time. Rather
  -- than invent a time and then quietly present the invention as fact, those
  -- rows are stamped at local midday (far enough from either midnight that no
  -- timezone shift can roll them onto the wrong day) and flagged here, so the
  -- UI can show a date alone and mean it.
  time_known   boolean not null default true,

  created_at   timestamptz not null default now(),

  -- Wide enough for any human, narrow enough to catch a slipped decimal
  -- point or a reading typed in pounds.
  constraint body_weights_sane check (weight_kg > 20 and weight_kg < 500)
);

-- The one access pattern: this user's readings, newest first.
create index if not exists body_weights_user_measured_idx
  on public.body_weights (user_id, measured_at desc);


-- ===========================================================================
-- 6. Lock an exercise's type once sets exist
-- ===========================================================================
-- Standing rule from CLAUDE.md. Enforced here rather than in the UI because
-- the database is the only place that can't be bypassed.

create or replace function public.lock_exercise_type()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if new.type is distinct from old.type
     and exists (select 1 from public.sets where exercise_id = old.id) then
    raise exception
      'Cannot change the type of "%" — sets have already been logged against it.',
      old.name
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

drop trigger if exists exercises_lock_type on public.exercises;

create trigger exercises_lock_type
  before update of type on public.exercises
  for each row
  execute function public.lock_exercise_type();

-- Same reasoning, lighter stakes: unilateral doesn't feed PR/index math, but
-- an old set's limiting_side only means something if you know whether the
-- exercise was tracked per-side when it was logged. Kept as its own
-- function/trigger rather than folded into lock_exercise_type above, since
-- the two lock for different reasons and touching the working type trigger
-- isn't worth the risk for this.
create or replace function public.lock_exercise_unilateral()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if new.unilateral is distinct from old.unilateral
     and exists (select 1 from public.sets where exercise_id = old.id) then
    raise exception
      'Cannot change whether "%" is unilateral — sets have already been logged against it.',
      old.name
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

drop trigger if exists exercises_lock_unilateral on public.exercises;

create trigger exercises_lock_unilateral
  before update of unilateral on public.exercises
  for each row
  execute function public.lock_exercise_unilateral();


-- ===========================================================================
-- 7. Row Level Security
-- ===========================================================================
-- RLS on with no policies returns an empty result and NO error. That is the
-- trap. So every table below gets RLS turned on AND explicit policies in the
-- same breath.
--
-- Two details that matter in every policy:
--
--   `to authenticated`   — the anon role is left with no policy at all, so a
--                          logged-out visitor can never read anything.
--
--   `(select auth.uid())`— wrapping it in a select lets Postgres work the
--                          value out once per query instead of once per row.
--
-- Policies are written one per operation (select / insert / update / delete)
-- rather than as a single `for all`, so that when something misbehaves you can
-- see exactly which operation is at fault.

alter table public.sessions          enable row level security;
alter table public.movement_patterns enable row level security;
alter table public.exercises         enable row level security;
alter table public.session_exercises enable row level security;
alter table public.sets              enable row level security;
alter table public.body_weights      enable row level security;
alter table public.session_types     enable row level security;


-- --- grants -----------------------------------------------------------------
-- Enabling RLS is not enough on its own — RLS only filters rows on a table
-- the role is already allowed to touch. Tables created by hand in the SQL
-- editor don't automatically get that base permission, so without this
-- block every request fails with "permission denied for table …" before
-- RLS policies are ever even consulted.
--
-- Only `authenticated` gets a grant. `anon` gets nothing at all — it doesn't
-- need one, since every policy above is `to authenticated` and anon has no
-- matching policy either way. No grant is one less thing that could go wrong
-- later.

grant select, insert, update, delete on public.sessions          to authenticated;
grant select, insert, update, delete on public.movement_patterns to authenticated;
grant select, insert, update, delete on public.exercises         to authenticated;
grant select, insert, update, delete on public.session_exercises to authenticated;
grant select, insert, update, delete on public.sets              to authenticated;
grant select, insert, update, delete on public.body_weights      to authenticated;
grant select, insert, update, delete on public.session_types     to authenticated;


-- --- sessions ---------------------------------------------------------------
-- Directly owned: the row carries user_id, so the check is a straight match.

drop policy if exists sessions_select_own on public.sessions;
create policy sessions_select_own on public.sessions
  for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists sessions_insert_own on public.sessions;
create policy sessions_insert_own on public.sessions
  for insert to authenticated
  with check (user_id = (select auth.uid()));

drop policy if exists sessions_update_own on public.sessions;
create policy sessions_update_own on public.sessions
  for update to authenticated
  using (user_id = (select auth.uid()))
  -- Stops a row being edited into someone else's ownership.
  with check (user_id = (select auth.uid()));

drop policy if exists sessions_delete_own on public.sessions;
create policy sessions_delete_own on public.sessions
  for delete to authenticated
  using (user_id = (select auth.uid()));


-- --- movement_patterns -------------------------------------------------------
-- Directly owned, same shape as sessions.

drop policy if exists movement_patterns_select_own on public.movement_patterns;
create policy movement_patterns_select_own on public.movement_patterns
  for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists movement_patterns_insert_own on public.movement_patterns;
create policy movement_patterns_insert_own on public.movement_patterns
  for insert to authenticated
  with check (user_id = (select auth.uid()));

drop policy if exists movement_patterns_update_own on public.movement_patterns;
create policy movement_patterns_update_own on public.movement_patterns
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists movement_patterns_delete_own on public.movement_patterns;
create policy movement_patterns_delete_own on public.movement_patterns
  for delete to authenticated
  using (user_id = (select auth.uid()));


-- --- exercises --------------------------------------------------------------
-- Writes additionally prove the movement pattern (if any) is yours, so an
-- exercise can't be filed into somebody else's box.

drop policy if exists exercises_select_own on public.exercises;
create policy exercises_select_own on public.exercises
  for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists exercises_insert_own on public.exercises;
create policy exercises_insert_own on public.exercises
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and (
      movement_pattern_id is null
      or exists (
        select 1 from public.movement_patterns mp
        where mp.id = exercises.movement_pattern_id
          and mp.user_id = (select auth.uid())
      )
    )
  );

drop policy if exists exercises_update_own on public.exercises;
create policy exercises_update_own on public.exercises
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (
    user_id = (select auth.uid())
    and (
      movement_pattern_id is null
      or exists (
        select 1 from public.movement_patterns mp
        where mp.id = exercises.movement_pattern_id
          and mp.user_id = (select auth.uid())
      )
    )
  );

drop policy if exists exercises_delete_own on public.exercises;
create policy exercises_delete_own on public.exercises
  for delete to authenticated
  using (user_id = (select auth.uid()));


-- --- session_exercises ------------------------------------------------------
-- No user_id of its own, so ownership is proved through the parent session.
-- Writes additionally prove the exercise is yours, so a comment can't be
-- attached to somebody else's exercise.

drop policy if exists session_exercises_select_own on public.session_exercises;
create policy session_exercises_select_own on public.session_exercises
  for select to authenticated
  using (
    exists (
      select 1 from public.sessions s
      where s.id = session_exercises.session_id
        and s.user_id = (select auth.uid())
    )
  );

drop policy if exists session_exercises_insert_own on public.session_exercises;
create policy session_exercises_insert_own on public.session_exercises
  for insert to authenticated
  with check (
    exists (
      select 1 from public.sessions s
      where s.id = session_exercises.session_id
        and s.user_id = (select auth.uid())
    )
    and exists (
      select 1 from public.exercises e
      where e.id = session_exercises.exercise_id
        and e.user_id = (select auth.uid())
    )
  );

drop policy if exists session_exercises_update_own on public.session_exercises;
create policy session_exercises_update_own on public.session_exercises
  for update to authenticated
  using (
    exists (
      select 1 from public.sessions s
      where s.id = session_exercises.session_id
        and s.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1 from public.sessions s
      where s.id = session_exercises.session_id
        and s.user_id = (select auth.uid())
    )
    and exists (
      select 1 from public.exercises e
      where e.id = session_exercises.exercise_id
        and e.user_id = (select auth.uid())
    )
  );

drop policy if exists session_exercises_delete_own on public.session_exercises;
create policy session_exercises_delete_own on public.session_exercises
  for delete to authenticated
  using (
    exists (
      select 1 from public.sessions s
      where s.id = session_exercises.session_id
        and s.user_id = (select auth.uid())
    )
  );


-- --- sets -------------------------------------------------------------------
-- Same idea: ownership comes from the parent session. Writes also check the
-- exercise, so a set can't be logged against an exercise you don't own.

drop policy if exists sets_select_own on public.sets;
create policy sets_select_own on public.sets
  for select to authenticated
  using (
    exists (
      select 1 from public.sessions s
      where s.id = sets.session_id
        and s.user_id = (select auth.uid())
    )
  );

drop policy if exists sets_insert_own on public.sets;
create policy sets_insert_own on public.sets
  for insert to authenticated
  with check (
    exists (
      select 1 from public.sessions s
      where s.id = sets.session_id
        and s.user_id = (select auth.uid())
    )
    and exists (
      select 1 from public.exercises e
      where e.id = sets.exercise_id
        and e.user_id = (select auth.uid())
    )
  );

drop policy if exists sets_update_own on public.sets;
create policy sets_update_own on public.sets
  for update to authenticated
  using (
    exists (
      select 1 from public.sessions s
      where s.id = sets.session_id
        and s.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1 from public.sessions s
      where s.id = sets.session_id
        and s.user_id = (select auth.uid())
    )
    and exists (
      select 1 from public.exercises e
      where e.id = sets.exercise_id
        and e.user_id = (select auth.uid())
    )
  );

drop policy if exists sets_delete_own on public.sets;
create policy sets_delete_own on public.sets
  for delete to authenticated
  using (
    exists (
      select 1 from public.sessions s
      where s.id = sets.session_id
        and s.user_id = (select auth.uid())
    )
  );


-- --- body_weights ------------------------------------------------------------
-- Directly owned, same shape as sessions.

drop policy if exists body_weights_select_own on public.body_weights;
create policy body_weights_select_own on public.body_weights
  for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists body_weights_insert_own on public.body_weights;
create policy body_weights_insert_own on public.body_weights
  for insert to authenticated
  with check (user_id = (select auth.uid()));

drop policy if exists body_weights_update_own on public.body_weights;
create policy body_weights_update_own on public.body_weights
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists body_weights_delete_own on public.body_weights;
create policy body_weights_delete_own on public.body_weights
  for delete to authenticated
  using (user_id = (select auth.uid()));


-- --- session_types ------------------------------------------------------------
-- Directly owned, same shape as sessions.

drop policy if exists session_types_select_own on public.session_types;
create policy session_types_select_own on public.session_types
  for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists session_types_insert_own on public.session_types;
create policy session_types_insert_own on public.session_types
  for insert to authenticated
  with check (user_id = (select auth.uid()));

drop policy if exists session_types_update_own on public.session_types;
create policy session_types_update_own on public.session_types
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists session_types_delete_own on public.session_types;
create policy session_types_delete_own on public.session_types
  for delete to authenticated
  using (user_id = (select auth.uid()));


-- ===========================================================================
-- 8. Health check
-- ===========================================================================
-- Run this after the rest. Every row must read: rls_enabled = true AND
-- policy_count = 4. A table with RLS on and 0 policies is the silent-empty
-- trap — it returns no rows and no error, and looks identical to "no data yet".

-- select
--   c.relname                        as table_name,
--   c.relrowsecurity                 as rls_enabled,
--   count(p.policyname)              as policy_count,
--   string_agg(p.policyname, ', ' order by p.policyname) as policies
-- from pg_class c
-- join pg_namespace n on n.oid = c.relnamespace
-- left join pg_policies p on p.schemaname = n.nspname and p.tablename = c.relname
-- where n.nspname = 'public'
--   and c.relname in ('sessions', 'movement_patterns', 'exercises', 'session_exercises', 'sets', 'body_weights', 'session_types')
-- group by c.relname, c.relrowsecurity
-- order by c.relname;

-- The other half of the check: does `authenticated` actually hold the grant?
-- Every row should list all four: DELETE, INSERT, SELECT, UPDATE.

-- select
--   table_name,
--   string_agg(privilege_type, ', ' order by privilege_type) as grants
-- from information_schema.role_table_grants
-- where table_schema = 'public'
--   and grantee = 'authenticated'
--   and table_name in ('sessions', 'movement_patterns', 'exercises', 'session_exercises', 'sets', 'body_weights', 'session_types')
-- group by table_name
-- order by table_name;
